// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DemandData: typeof import('./src/components/DemandData.vue')['default']
    DemandParams: typeof import('./src/components/DemandParams.vue')['default']
    DemandPlot: typeof import('./src/components/DemandPlot.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
  }
}

export { }
